name: Handle Deployment

on:
  deployment:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Print deployment info
      run: |
        echo "Deployment triggered by ${{ github.actor }}"
        echo "Repository: ${{ github.repository }}"
        echo "Environment: ${{ github.event.deployment.environment }}"
        echo "Ref: ${{ github.event.deployment.ref }}"
    
    - name: Mark deployment as successful
      uses: bobheadxi/deployments@v1
      with:
        step: finish
        token: ${{ secrets.GITHUB_TOKEN }}
        status: success
